"""NumPy oracle draws are independent of the shared implementation under test."""
from dataclasses import replace
import numpy as np
import pytest
from bike_sim.sim.research.sensor_noise import NoiseTape, SensorNoiseSource, build_noise_tape
from bike_sim.sim.research.sensors import SensorConfig, SensorPipeline


def legacy_draws(config, seed, count):
    noise_seed, dropout_seed = np.random.SeedSequence(seed).spawn(2)
    noise_rng = np.random.default_rng(noise_seed)
    dropout_rng = np.random.default_rng(dropout_seed)
    rows, uniforms = [], []
    for _ in range(count):
        acceleration = noise_rng.normal(0., config.acceleration_std_mps2, 3)
        gyro = noise_rng.normal(0., config.gyro_std_rad_s)
        encoder = noise_rng.normal(0., config.encoder_std_rad_s, 3)
        torque = noise_rng.normal(0., config.torque_std_nm, 2)
        rows.append([*acceleration, gyro, *encoder, *torque])
        uniforms.append(dropout_rng.random())
    return np.asarray(rows), np.asarray(uniforms)


@pytest.mark.parametrize('seed', [0, 19, 2**63+11])
@pytest.mark.parametrize('config', [SensorConfig(), SensorConfig.ideal(),
    replace(SensorConfig(), acceleration_std_mps2=0., gyro_std_rad_s=0., imu_enabled=False)])
def test_exact_legacy_call_order(config, seed):
    tape = build_noise_tape(config, seed=seed, count=128)
    noise, uniform = legacy_draws(config, seed, 128)
    np.testing.assert_array_equal(tape.noise, noise)
    np.testing.assert_array_equal(tape.dropout_uniform, uniform)


def test_zero_scales_and_imu_switch_do_not_shift_other_channels():
    base = SensorConfig()
    reference = build_noise_tape(base, seed=31, count=64)
    masked = build_noise_tape(replace(base, imu_enabled=False,
        acceleration_std_mps2=0., gyro_std_rad_s=0.), seed=31, count=64)
    np.testing.assert_array_equal(reference.noise[:, 4:], masked.noise[:, 4:])
    np.testing.assert_array_equal(reference.dropout_uniform, masked.dropout_uniform)


def test_draws_own_configuration_and_tape_owns_buffers():
    config = SensorConfig()
    source = SensorNoiseSource(config, seed=0)
    assert source.config is not config
    noise, dropout = np.ones((2, 9)), np.full(2, .25)
    tape = NoiseTape(noise, dropout)
    noise.fill(99.)
    dropout.fill(.99)
    np.testing.assert_array_equal(tape.noise, np.ones((2, 9)))
    np.testing.assert_array_equal(tape.dropout_uniform, [.25, .25])
    assert not tape.noise.flags.writeable
    assert not tape.dropout_uniform.flags.writeable
    with pytest.raises(ValueError):
        tape.noise[0, 0] = 0.


@pytest.mark.parametrize('noise,dropout', [
    (np.zeros((0, 8)), np.zeros(0)), (np.zeros(9), np.zeros(1)),
    (np.zeros((1, 9)), [1.]), (np.zeros((1, 9)), [-.1]),
    (np.zeros((1, 9)), [np.nan]), (np.full((1, 9), np.inf), [.5]),
    (np.ones((1, 9), dtype=bool), [.5]), (np.zeros((1, 9)), [True]),
    (np.zeros((1, 9), dtype=complex), [.5]), (np.full((1, 9), '0'), [.5]),
])
def test_invalid_tape_domain(noise, dropout):
    with pytest.raises(ValueError):
        NoiseTape(noise, dropout)


@pytest.mark.parametrize('seed', [True, -1, .5, '3'])
def test_invalid_seed(seed):
    with pytest.raises(ValueError):
        build_noise_tape(SensorConfig(), seed=seed, count=1)


@pytest.mark.parametrize('count', [True, -1, 1.5])
def test_invalid_count(count):
    with pytest.raises(ValueError):
        build_noise_tape(SensorConfig(), seed=0, count=count)


def test_reads_and_invalid_push_do_not_consume_rng(raw_sensor):
    config = replace(SensorConfig(), latency_s=0.)
    a, b = SensorPipeline(config, seed=23), SensorPipeline(config, seed=23)
    a.reset(raw_sensor())
    b.reset(raw_sensor())
    assert a.read(0.) == a.read(0.)
    with pytest.raises(ValueError):
        a.push(raw_sensor())
    a.push(raw_sensor(.01))
    b.push(raw_sensor(.01))
    assert a.read(.01) == b.read(.01)


def test_pipeline_matches_frozen_pre_refactor_sensor_trace(raw_sensor, assert_tree):
    # The old pipeline is retained verbatim; expected draws/queue behavior do
    # not call the refactored helper. No golden values were generated by a run
    # during this source-only delivery.
    from dataclasses import asdict
    import _legacy_sensor_oracle as legacy
    config = replace(SensorConfig(), latency_s=.007, maximum_age_s=.012,
        acceleration_bias_mps2=(.1, -.2, .3), gyro_bias_rad_s=.004,
        dropout_probability=.35, imu_enabled=False)
    reference = legacy.SensorPipeline(legacy.SensorConfig(**asdict(config)), seed=210)
    actual = SensorPipeline(config, seed=210)
    reference.reset(legacy.SensorObservation(**asdict(raw_sensor())))
    actual.reset(raw_sensor())
    for index in range(20):
        time_s = index*.005
        if index:
            reference.push(legacy.SensorObservation(**asdict(raw_sensor(time_s))))
            actual.push(raw_sensor(time_s))
        for now in (time_s, time_s+.001, time_s+.001):
            assert_tree(asdict(actual.read(now)), asdict(reference.read(now)), atol=0., rtol=0.)
    assert actual.samples_attempted == reference.samples_attempted
    assert actual.samples_dropped == reference.samples_dropped
